### ISSUE TITLE
Missing Relics (not sure which mod added these)

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#10]
a few days ago I ran into a duo of relics that were actually pretty interesting, one of them I cannot remember the name of, but it lowered all damage you took by one, meaning torii now would negate all damage of 5 and bellow, a solid relic overall.

The other was named Homunculus and prevented you from losing health from cards you owned, so Rupture would no longer work at all with this relic, but you would not take damage from playing cards like Offering.

Both these relics are now nowhere to be seen and I was wondering if they were removed on purpose or if the mod that added them (Fruity, BaseMod or MoreRelics might have had an update that removed them.

Either way I would like to see these relics restored as I had an idea for a deck that requires both heck if the idea works as I hope we might have another deck archetype going.

**Comment by daviscook477** [comment]
They were in FruityMod and not exactly intended to be put out. They had just been left in the codebase from some initial testing that was done. The reason that you can no longer find them is that they have been removed. You can still find the code on Github if you want to duplicate the effects and add them in yourself.

**Comment by Lunaraia** [comment]
while I would love to, my ability to comprehend code are about as great as my ability to fly... non-existent, only reason I could make head or tails of the exception errors was because the culprits were named by the error log XD.

So instead I am gonna be requesting that they get added in at a later date or something as I have no clue how to add them myself
