### ISSUE TITLE
How to Override vanilla card?

### ISSUE THREAD

**Issue by Villfuk02** [daviscook477/BaseMod#100]
Pretty self explanatory. I'd like to Change burns, so they don't deal straight up damage, but apply Burning instead (my custom power).

**Comment by Villfuk02** [comment]
Btw if it is possible, I'd also like to override how the reptomancer works.

**Comment by Villfuk02** [comment]
I've found out, that I can just use 'SpirePatch', but I have no idea how. I think there could be a simple explanation page in the Wiki.

**Comment by Kobting** [comment]
SpirePatch is from ModTheSpire. Here's that [Wiki](https://github.com/kiooeht/ModTheSpire/wiki)

**Comment by Villfuk02** [comment]
Thanks!
