### ISSUE TITLE
Images were aliasing after scaling down

### ISSUE THREAD

**Issue by lionpkqq** [daviscook477/BaseMod#103]
I am playing under the 1600x900 resolution and using a 1920x1200 image as the character select screen background. I found that the image, as well as my other custom art resource (like card illustrations, energy icons, etc), has become very jaggy. Is there a way to solve this problem?

**Comment by kiooeht** [comment]
I think this has to do with texture filters. If you use `ImageMaster.loadImage` to load any images it sets the texture filter to linear, which I think will solve the jagged issue.

**Comment by lionpkqq** [comment]
**I am not sure how to use ImageMaster.loadImage, since I use something like** 
`super(ID, NAME, **BlackRuseMod.makePath(BlackRuseMod.KIDNEY_SHOT)**, COST, DESCRIPTION, AbstractCard.CardType.ATTACK,
				AbstractCardEnum.SILVER, AbstractCard.CardRarity.BASIC,
				AbstractCard.CardTarget.ENEMY);`
to load my card illustrations.

**Besides, I found that the CustomCard has already set the filter to linear:**
`public void loadCardImage(String img) {
		Texture cardTexture;
		if (imgMap.containsKey(img)) {
			cardTexture = imgMap.get(img);
		} else {
			cardTexture = new Texture(img);
			imgMap.put(img, cardTexture);
		}
		**cardTexture.setFilter(Texture.TextureFilter.Linear,  Texture.TextureFilter.Linear);**
		int tw = cardTexture.getWidth();
		int th = cardTexture.getHeight();
		TextureAtlas.AtlasRegion cardImg = new AtlasRegion(cardTexture, 0, 0, tw, th);
		ReflectionHacks.setPrivateInherited(this, CustomCard.class, "portrait", cardImg);
	}`
**but I still got the aliasing.**

**Comment by lionpkqq** [comment]
This is a common issue which also happened to other modders I know.

**Comment by lionpkqq** [comment]
If simply setting texture filter to linear will solve the issue, can you update the basemod so that we don't have to patch everything by ourselves?

**Comment by lionpkqq** [comment]
One modder told me that using this patch:
`@SpirePatch(cls = "com.megacrit.cardcrawl.screens.charSelect.CharacterOption", method = "updateHitbox")
    public static class UpdateHitboxBgImgFix
    {
        @SpireInsertPatch(rloc = 40)
        public static void Insert(final CharacterOption _inst) {
            CardCrawlGame.mainMenuScreen.charSelectScreen.bgCharImg.setFilter(Texture.TextureFilter.Linear, Texture.TextureFilter.Linear);
        }
    }`
 would fix the character select screen image. I tried it and it actually worked.
