### ISSUE TITLE
mod the spire wont work(could be base mod problem)

### ISSUE THREAD

**Issue by Downanddirty4568** [daviscook477/BaseMod#123]
![errormessage1](https://user-images.githubusercontent.com/38453823/45039928-97aa6e00-b019-11e8-9b12-f487fc1b1e77.jpg)
![untitled](https://user-images.githubusercontent.com/38453823/45039933-9a0cc800-b019-11e8-84c0-1155c1151fb8.jpg)
ever since the update that is titled "the one that breaks everything" for mod the spire
 it has done exactly that although i don't know if its a problem with modthespire or a problem with base mod but basically i have continuously downloaded the latest of the latest versions of every single mod i have and that is what keeps breaking it so im hoping u can help

**Comment by kiooeht** [comment]
Custom Cards is known not to work. Disable it and it should work.

You also don't need the Custom Climb mod anymore since the base game has Custom Mode.

**Comment by Downanddirty4568** [comment]
![customcards](https://user-images.githubusercontent.com/38453823/45056893-0521c300-b049-11e8-9f66-fc2ba4f54a0e.jpg)
known to not work?? there is literally no issues recorded under it, It did fix it but its not obvious
