### ISSUE TITLE
I'm trying to make a mod, but i get this error when I try to add a custom relic 

### ISSUE THREAD

**Issue by ProfElements** [daviscook477/BaseMod#128]
BaseMod: 3.2.2
Slay The Spire Weekly Patch 41
Window 10
(Is there anything else i need then please tell me)

21:10:29.000 INFO basemod.BaseMod> initializeCardTags
21:10:29.007 INFO basemod.BaseMod> Making AutoTag: basemod.helpers.BaseModTags.BASIC_STRIKE
21:10:29.021 INFO basemod.BaseMod> Making AutoTag: basemod.helpers.BaseModTags.BASIC_DEFEND
21:10:29.024 INFO basemod.BaseMod> Making AutoTag: basemod.helpers.BaseModTags.GREMLIN_MATCH
21:10:29.025 INFO basemod.BaseMod> Making AutoTag: basemod.helpers.BaseModTags.STRIKE
21:10:29.034 INFO basemod.BaseMod> Making AutoTag: basemod.helpers.BaseModTags.FORM
21:10:29.043 INFO basemod.BaseMod> initializeGson
21:10:29.047 INFO basemod.BaseMod> initializeTypeMaps
21:10:29.049 INFO basemod.BaseMod> Registered MonsterStrings
21:10:29.051 INFO basemod.BaseMod> Registered PowerStrings
21:10:29.052 INFO basemod.BaseMod> Registered CardStrings
21:10:29.053 INFO basemod.BaseMod> Registered RelicStrings
21:10:29.054 INFO basemod.BaseMod> Registered EventStrings
21:10:29.055 INFO basemod.BaseMod> Registered PotionStrings
21:10:29.056 INFO basemod.BaseMod> Registered CreditStrings
21:10:29.057 INFO basemod.BaseMod> Registered TutorialStrings
21:10:29.057 INFO basemod.BaseMod> Registered KeywordStrings
21:10:29.058 INFO basemod.BaseMod> Registered ScoreBonusStrings
21:10:29.059 INFO basemod.BaseMod> Registered CharacterStrings
21:10:29.060 INFO basemod.BaseMod> Registered UIStrings
21:10:29.060 INFO basemod.BaseMod> Registered OrbStrings
21:10:29.061 INFO basemod.BaseMod> Registered RunModStrings
21:10:29.062 INFO basemod.BaseMod> Registered BlightStrings
21:10:29.063 INFO basemod.BaseMod> Registered AchievementStrings
21:10:29.063 INFO basemod.BaseMod> initializePowerMap
21:10:29.888 INFO basemod.BaseMod> initializeUnderscorePowerIDs
21:10:29.923 INFO desktop.DesktopLauncher> time: 1537305029923
21:10:29.924 INFO desktop.DesktopLauncher> version: 2018-09-06
21:10:29.924 INFO desktop.DesktopLauncher> libgdx:  1.9.5
21:10:29.924 INFO desktop.DesktopLauncher> default_locale: en_US
21:10:29.925 INFO desktop.DesktopLauncher> default_charset: windows-1252
21:10:29.925 INFO desktop.DesktopLauncher> default_encoding: Cp1252
21:10:29.926 INFO desktop.DesktopLauncher> java_version: 1.8.0_171
21:10:29.926 INFO desktop.DesktopLauncher> os_arch: amd64
21:10:29.926 INFO desktop.DesktopLauncher> os_name: Windows 10
21:10:29.927 INFO desktop.DesktopLauncher> os_version: 10.0
21:10:29.929 INFO core.SystemStats> MEMORY STATS:
Free Memory: 155Mb
Max Memory: 1,794Mb
Allocated Memory: 419Mb
Unallocated Memory: 1,375Mb
Total Free Memory: 1,530Mb
Used Memory: 263Mb

21:10:29.930 INFO core.SystemStats> DISK STATS:
Total Space: 463,910Mb
Usable Space: 290,084Mb
Free Space: 290,084Mb
21:10:37.055 INFO panels.TopPanel> Not starting twitch integration because enabled=false
21:10:37.752 INFO helpers.CardLibrary> Card load time: 1436ms with 283 cards
21:10:37.758 INFO basemod.BaseMod> begin editing relics
21:10:37.774 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.relics.AbstractRelic.<init>(AbstractRelic.java:123) ~[?:?]
	at basemod.abstracts.CustomRelic.<init>(CustomRelic.java:10) ~[BaseMod.jar:?]
	at io.profelements.examplemod.relics.Blueberries.<init>(Blueberries.java:15) ~[ExampleMod.jar:?]
	at io.profelements.examplemod.ExampleMod.receiveEditRelics(ExampleMod.java:34) ~[ExampleMod.jar:?]
	at basemod.BaseMod.publishEditRelics(BaseMod.java:2365) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.helpers.RelicLibrary.EditRelicsPatch.Prefix(EditRelicsPatch.java:12) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.helpers.RelicLibrary.initialize(RelicLibrary.java) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:289) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by kiooeht** [comment]
You have to have RelicStrings set up otherwise your relics will crash

```Java
@Override
public void receiveEditStrings()
{
    BaseMod.loadCustomStringsFile(RelicStrings.class, "<path_to_your_relic_strings>.json");
}
```

JSON file:
```
{
  "RelicID": {
    "NAME": "RelicName",
    "FLAVOR": "Flavor text",
    "DESCRIPTIONS": [
      "Foo",
      "Bar"
    ]
  }
}
```

**Comment by ProfElements** [comment]
Thank You! I wondered why people has a relics.json Thank You!
