### ISSUE TITLE
receivePostPotionUse is called once per Relics you have.

### ISSUE THREAD

**Issue by Celicath** [daviscook477/BaseMod#136]
Whenever you use a Potion, receivePostPotionUse is called once per Relics you have. So if you have 4 relics, it is called 4 times. I think it should be called only once.

Maybe rloc of PostPotionUseHook needs to be changed from 21 to 23. I guess it happened because of code change of base game?

Edit: Also PostPotionUseHookTargetMode needs to be fixed.

**Comment by kiooeht** [comment]
This was an interesting bug. Turns out it has existed since the May 24th update of the game.
