### ISSUE TITLE
Can I modify existing cards with this?

### ISSUE THREAD

**Issue by felix91gr** [daviscook477/BaseMod#138]
Hi! Sorry if I shouldn't be asking here, please direct me to where I should if that's the case.

I'm interested in making a mod that plays with the idea of rebalancing some of the base game's cards, like Rupture and Fusion.

Could I do that with the BaseMod? :)

**Comment by kiooeht** [comment]
Best place to ask questions is the unsupported-modding channel on the official discord (https://discord.gg/SlayTheSpire).

You can edit existing cards either by:
* Patching them using SpirePatches (https://github.com/kiooeht/ModTheSpire/wiki/SpirePatch).
* Or creating your own version with BaseMod and using the same ID so your version overrides the base version.

**Comment by felix91gr** [comment]
Thank you, will do and will check out as well! :)
