### ISSUE TITLE
Unusual but Consistent Crash even after re-install

### ISSUE THREAD

**Issue by ZanderTheUnthonkable** [daviscook477/BaseMod#139]
![capture](https://user-images.githubusercontent.com/42562735/46878318-946c8400-ce08-11e8-887c-1d5f36bd022f.PNG)
Prevents any mods which have BaseMod dependency, i.e. almost all of them. 
Game loads fine without BaseMod
Was working fine 2 days ago.
Attempts to fix:
Re-installing Mod The Spire and BaseMod
Deleting both mods and re-installing
Reverting to a previous version of slay the spire
Not really sure where to go from here.

**Comment by kiooeht** [comment]
Yesterday's update to the game brought a lot of backend changes to the game that break BaseMod in a lot of ways. I've been working on fixing it, but there are a lot of changes to work through, it will take some time.

**Comment by ZanderTheUnthonkable** [comment]
Ah got it.
Not a problem,just wanted to make sure i wasn't being blind and missing something obvious.
Best of luck in fixing it, i know just how hard these kind of foxes can be
