### ISSUE TITLE
Crash with new version of StS?

### ISSUE THREAD

**Issue by FinderOfWays1** [daviscook477/BaseMod#147]
Trying to run MTS with only basemod on causes an error on launch:

Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_171)
 - Slay the Spire (10-18-2018)
 - ModTheSpire (3.4.0)
Mod list:
 - basemod (4.0.2)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetColorSpecificCardSwitch:
No method [getColorSpecificCard(com.megacrit.cardcrawl.characters.AbstractPlayer$PlayerClass, com.megacrit.cardcrawl.random.Random)] found on
class [com.megacrit.cardcrawl.helpers.CardLibrary]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:271)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)

Additionally, the search for updates button seems to be non-functional for me. When pressed, a 'loading' icon appears next to each mod, but is frozen and no progress seems to be made. Button appears like the loading icon temporarily, but quickly goes back to initial state and no search for updates occurs.

**Comment by kiooeht** [comment]
You need to update to the latest version of BaseMod (https://github.com/daviscook477/BaseMod/releases/latest).

The updater isn't working for you because it has a rate limit of 60 requests per hour (each mod is a request). If it freezes, just wait an hour before trying again.
