### ISSUE TITLE
Bug when chosing "Shiny" and "Diverse",  get 2 copies of every rare card

### ISSUE THREAD

**Issue by prttt26** [daviscook477/BaseMod#153]
And with "colorless card", I got 4 copies of colorless rare cards. 
![2018-11-02 2](https://user-images.githubusercontent.com/40000661/47938320-1442b700-deba-11e8-99fd-ac1fd5ba80b5.png)
![2018-11-02 1](https://user-images.githubusercontent.com/40000661/47938324-186ed480-deba-11e8-8948-18974523acb9.png)

**Comment by kiooeht** [comment]
Just so you know, there's a bug in the base game where using both "Shiny" and "Colorless Cards" gives you two copies of every rare colorless card.
