### ISSUE TITLE
Dynamic Variable upgrade color is wrong in Smith View

### ISSUE THREAD

**Issue by Skrelpoid** [daviscook477/BaseMod#173]
Like the title says, the color of a value that is upgraded is wrong in the Smith View (where you go after you click on Smith on a camp fire)
The color is correct in the card inspect view: 
![screenshot_11](https://user-images.githubusercontent.com/22478595/50643285-e2a7a400-0f6d-11e9-96bb-1306daf68a97.png)
but not in the smith view: 
![screenshot_12](https://user-images.githubusercontent.com/22478595/50643301-f05d2980-0f6d-11e9-8a9f-3ca75eb4776e.png)

**Comment by kiooeht** [comment]
So you know, once it's released, you will have to override a new method on DynamicVariable called `setIsModified` in order for the smith view to work for your dynamic variables.

**Comment by Skrelpoid** [comment]
So in the setIsModified i have to set a value so isModified returns true for the card, correct?

**Comment by kiooeht** [comment]
Correct.

**Comment by kiooeht** [comment]
It's back in v5.7.1 on the Workshop.
