### ISSUE TITLE
onExhaust() only procs for powers on the player

### ISSUE THREAD

**Issue by sewvi** [daviscook477/BaseMod#190]
Basically I wanted to make a debuff (i.e. an AbstractPower) that deals damage and goes down by 1 every time a card is exhausted. However while testing I realized the onExhaust(AbstractCard card) method of AbstractPower is only called for powers that are on the player, and not for powers that are on monsters.

**Comment by kiooeht** [comment]
[StSLib](https://steamcommunity.com/sharedfiles/filedetails/?id=1609158507) now has a `BetterOnExhaustPower`, that works for powers that are on monsters.
