### ISSUE TITLE
Custom characters show the upper case character ID in the run history

### ISSUE THREAD

**Issue by twanvl** [daviscook477/BaseMod#20]
For instance with the hybrid character mod you see "HYBRID" in the run history, and with fruitymod you see "SEEKER" instead of "The Seeker".

**Comment by daviscook477** [comment]
I'll look into patching the run history screen sometime this week most likely.

**Comment by daviscook477** [comment]
Fixed with https://github.com/daviscook477/BaseMod/commit/ef83b3fcfad422b9f1fbf999c7998eb54cfe8b2d
