### ISSUE TITLE
BaseMod Changes Enemy Encounter RNG

### ISSUE THREAD

**Issue by ForgottenArbiter** [daviscook477/BaseMod#229]
With no other mods enabled, BaseMod causes different encounters to be generated compared to the unmodded game after Act 1. This is caused by an additional monsterRng value being used in the CustomBosses patch:

https://github.com/daviscook477/BaseMod/blob/08fbd6f8695097b495bec2bc2b3c765fe0b83a6a/mod/src/main/java/basemod/patches/com/megacrit/cardcrawl/dungeons/AbstractDungeon/CustomBosses.java#L55

**Comment by al233a** [comment]
.
