### ISSUE TITLE
ID changes for updated items?

### ISSUE THREAD

**Issue by VoodooPuppet** [daviscook477/BaseMod#24]
For example trying to add the upgrade of cloak and dagger:  "deck add Cloak And Dagger 1 1"  only gives you the normal card. 
same thing happens for Flash of Steel 1 1 

is their another ID for the upgrade ?

thank you!

**Comment by Lunaraia** [comment]
how it works are that it gives upgrade levels, so deck add Cloak And Dagger 1 1 will give you an upgrade level 1 card (default level) deck add Cloak And Dagger 1 2 or higher will give you the upgraded version

**Comment by daviscook477** [comment]
This definitely seems like a bug.

**Comment by daviscook477** [comment]
The intended behavior is that `deck add Cloak And Dagger 1` or `deck add Cloak And Dagger 1 0` would give you an unupgraded card.

**Comment by Lunaraia** [comment]
strangely enough Searing Blow actually works differently, as I were just doing an ironclad run and decided to test it, using Deck Add Searing Blow 100 gives you a level 100 searing Blow, while Deck add Searing Blow 1 100 gives you a single level 1 Searing blow, I suspect the infinite upgrade levels are to blame

**Comment by daviscook477** [comment]
Just took a look at the code and I forgot to support cards with multiple tokens in their name so right now it's only working correctly for single word card names. I'll push a fix today.
