### ISSUE TITLE
Need Some Help

### ISSUE THREAD

**Issue by StevenTyler696** [daviscook477/BaseMod#25]
I'm having an issue with getting this mod installed correctly. I'm VERY unfamiliar with the "Building" process via maven. I've installed maven correctly, as well as eclipse, but I have no idea how to actually build the jar file in eclipse from there.

I found two prebuilt Jar files for ModTheSpire and BaseMod, but I get errors that prevent me from launching when I select "Base Mod". If I don't select any mods, the game launches fine.

Links for those mentioned files.
ModTheSpire - https://github.com/kiooeht/ModTheSpire/releases
BaseMod - https://github.com/t-larson/BaseMod/releases

I've attached the debug text from when it errors out, if that helps at all.

Any assistance is greatly appreciated! 

[debug.txt](https://github.com/daviscook477/BaseMod/files/1826002/debug.txt)

**Comment by Lunaraia** [comment]
to install the game correctly you need to have the newest versions of ModTheSpire.jar and BaseMod.jar, take Basemod from the release on Daviscook's repository as it's the one that is the most up to date, which you should have, then you go into the location of the game folder, which is as easy as going into Steam right clicking Slay the Spire and selecting properties then the Local files tab and then Browse Local Files.

Selecting Brose Local Files you should now be inside Slay The Spires main folder, this is where ModTheSpire goes, it has to be inside this folder to start properly, then you need to create a new folder called mods inside this directory and put BaseMod and any other mods you are using in there.

Then start ModTheSpire, here you can rearrange your mods, make sure BaseMod are on top of that list or the game won't start.

**Comment by daviscook477** [comment]
@StevenTyler696 is this issue resolved?

**Comment by StevenTyler696** [comment]
Sorry for the delay - I had a work trip. 

I downloaded the BaseMod jar file that you attached, and swapped it with the one I had originally linked. It worked like a charm.

Thank you very much!
