### ISSUE TITLE
Crash at startup under linux

### ISSUE THREAD

**Issue by spider312** [daviscook477/BaseMod#288]
[hs_err_pid10265.log](https://github.com/daviscook477/BaseMod/files/5899747/hs_err_pid10265.log)
[mts_launcher.log](https://github.com/daviscook477/BaseMod/files/5899748/mts_launcher.log)
[mts_process_launch.log](https://github.com/daviscook477/BaseMod/files/5899749/mts_process_launch.log)

Hi

I've been playing for some days with twitch integration mods, then it just stoped working. When i launch STS "with mods" it just does nothing, steam returning to "not playing" status after some seconds

Mods i used : 
 - Twitch Decklist Mod https://steamcommunity.com/sharedfiles/filedetails/?id=1774813184
 - Slay the Relics Exporter https://steamcommunity.com/sharedfiles/filedetails/?id=1989770578
 - BaseMod & Modthespire of course
 - Downfall Expansion Mod (but neved activated it) https://steamcommunity.com/sharedfiles/filedetails/?id=1610056683

Uninstaling those mods has no effect on crashes

Thanks in advance

**Comment by kiooeht** [comment]
This was an issue with ModTheSpire that I've now fixed (https://github.com/kiooeht/ModTheSpire/commit/93672a57af47f8d1c120cc230af87206114ea29d).
Note that the issue had to do with your mod list save file somehow becoming corrupted, so unfortunately any mod lists you've created will be gone and you'll have to remake them.

**Comment by spider312** [comment]
Thanks for the quick answer and fix, it seems to work :)
