### ISSUE TITLE
Can you give some tips about mvn package the example_mod in the tutorial?

### ISSUE THREAD

**Issue by glolionline** [daviscook477/BaseMod#37]
First, thanks for your excellent work on this mod/tool.
I followed your tutorial in "Getting Started (For Modders)", everything is good, but since I'm new to java..it's very confusing using the mvn, I know how to create new project and package a project followed a tutorial on youtube..But for this specific mod tutorial, I can't figure out how to package the example_mod, I tried to copy the pom.xml from basemod project to the example_mod and change some tags manually, but it didn't work, there are problems about the dependencies I guess. 
Is there a way to run the launcher in eclipse (like modding in minecraft) or can you offer some tips on how to mvn package the example_mod? I see there is a build guide about basemod, problem is the example_mod is not a mvn project from the start :(

**Comment by daviscook477** [comment]
Hey! Glad to see you were able to get started with it. I literally just got the example mod part of the tutorial done earlier today. I'm aware that it doesn't explain maven yet. I'm hopefully going to do that tomorrow. For now the best advice I have is to use `pom.xml` from a mod like FruityMod or something and try and modify the tags. You should be able to use the export to jar option that Eclipse has for this example mod. Maven is necessary for when your mod includes assets like images, localization, etc...

**Comment by glolionline** [comment]
Thanks for the tips, and I just realize why I didn't find the "Getting Started (For Modders)" page earlier, thought some thing was wrong with my eyes lol. 
Ok, I will try using the pom.xml from the FruityMod haha, btw, I was tring to add a zh_CN localization file for the FruityMod last night.

**Comment by glolionline** [comment]
Success! Using the pom.xml from FruityMod, tanks :)

**Comment by daviscook477** [comment]
Just as a heads up about some slightly disappointing information. BaseMod currently doesn't load localization files based on the language the game is set to so currently mods themselves are required to check the game language and load the appropriate localization file. Getting localization support done right is on my todo list.
