### ISSUE TITLE
Some console issues...

### ISSUE THREAD

**Issue by Vlad-00003** [daviscook477/BaseMod#40]
Actually there is a bit problems with the console. First - potions. There suppose to be a command ```potion list```. Here is the respose for it: 
![image](https://user-images.githubusercontent.com/31519848/38139962-6e072274-343a-11e8-8a54-0684ba32e87b.png)

Second problem - powers. If you use the command without args - you would get the arrow that does nothing. At all =) I think it's related to the lastes game update, but still.

**Comment by daviscook477** [comment]
If you're on patch 18 there could be any number of issues. BaseMod has not been updated yet. Thanks for the heads up about issues with the console.

**Comment by Vlad-00003** [comment]
Yep. Latest patch

**Comment by Vlad-00003** [comment]
Btw - the potion commaond use to work like that even before the update...

**Comment by daviscook477** [comment]
Got it. So that means the dev console is still kinda buggy. I'll fix both of those bugs.
