### ISSUE TITLE
Logging publishStartAct hundreds of times

### ISSUE THREAD

**Issue by gskleres** [daviscook477/BaseMod#41]
When playing ModTheSpire in the newest patch, the following line is logged literally hundreds and hundreds of times:

19:46:25.036 INFO basemod.BaseMod> publishStartAct

EDIT: The timestamp changes.

**Comment by daviscook477** [comment]
Fixed with https://github.com/daviscook477/BaseMod/commit/ca2e7dea3878c8cd3b000154472dc705251a0a5b

Will be available with next release of BaseMod
