### ISSUE TITLE
Game closes when entering the store

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#46]
as the title says the game closes when you enter the store, there are no errors anywhere so I am not completely sure whats up with it, might have something to do with the alterations of the ? Card from a Boss Relic to a Shop (I think) Relic, either way the game just dies the moment you try to enter a store, played with Ironclad when this happened.

Were using the following Mods: Mod list: basemod (2.4.0), ColoredMap, Custom Climb, MoreRelics, FruityMod, and the newest version of ModTheSpire.

Was a regular run on Ascension 1

**Comment by daviscook477** [comment]
Ah damnit. I'll have to make a hotfix. Thank you.

**Comment by daviscook477** [comment]
I couldn't reproduce the issue on a run with the Seeker either with or without the Question Card. And I couldn't reproduce it when playing as the Ironclad either. Might be an issue with MoreRelics? I couldn't reproduce it on Ascension 1 either...

**Comment by daviscook477** [comment]
I'm not saying the bug doesn't exist. I'm just saying I'm not sure what's causing it yet...

**Comment by Lunaraia** [comment]
it might be one of the other mods I am using will check it out once I have the time

**Comment by Lunaraia** [comment]
just in case this is relevant info here is what the bottom of the ModTheSpire console says jsut as the game self closes, this is with all the mods mentioned earlier active:

_______________

17:06:35.372 INFO dungeons.AbstractDungeon> Game Seed: -3240295108209065468
17:06:35.372 INFO dungeons.AbstractDungeon> Map generation time: 12ms
17:06:35.372 INFO dungeons.AbstractDungeon> Loading into: 2,1
17:06:35.373 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
17:06:35.374 INFO audio.MusicMaster> Playing SHOP
17:06:35.441 INFO shop.ShopScreen> ROLL 46
17:06:35.441 INFO dungeons.AbstractDungeon> Returning UNCOMMON relic
17:06:35.443 INFO shop.ShopScreen> ROLL 59
17:06:35.443 INFO dungeons.AbstractDungeon> Returning COMMON relic
17:06:35.445 INFO shop.ShopScreen> ROLL 53
17:06:35.446 INFO dungeons.AbstractDungeon> Returning COMMON relic
17:06:35.447 INFO basemod.BaseMod> postCreateShopRelics for: [com.megacrit.cardcrawl.shop.StoreRelic@31648f03, com.megacrit.cardcrawl.shop.StoreRelic@15578cbc, com.megacrit.cardcrawl.shop.StoreRelic@ba7d436]
17:06:35.448 INFO basemod.BaseMod> postCreateShopPotions for: [com.megacrit.cardcrawl.shop.StorePotion@61e96823, com.megacrit.cardcrawl.shop.StorePotion@54da164c, com.megacrit.cardcrawl.shop.StorePotion@545f161e]

________________

After testing a wee bit I found the culprit to be Custom Climb, not sure what it does but disabling it allowed me entrance into the shop without issue.

**Comment by daviscook477** [comment]
Thanks for investigating @Lunaraia . I'm glad things are working alright.
