### ISSUE TITLE
Base mod not working

### ISSUE THREAD

**Issue by Featherstone122** [daviscook477/BaseMod#63]
it keeps saying the base mod wont work
![screenshot 1](https://user-images.githubusercontent.com/39348153/40139394-93a3b062-5904-11e8-8eea-d35ba225522e.png)

**Comment by daviscook477** [comment]
Are you on the most up-to-date (non-beta) version of the game? I just downloaded the most recent version of basemod and sts_always_whale and my game launched without errors.

**Comment by daviscook477** [comment]
I see that you have an STS version of 05-15-18 but I don't think there's been any release for that date yet?

**Comment by gygrazok** [comment]
RegenerationPower has been removed from the beta branch, that's why it doesn't work. Non-beta should work fine.
