### ISSUE TITLE
Maven Tutorial

### ISSUE THREAD

**Issue by Skrelpoid** [daviscook477/BaseMod#67]
Hey I was wondering if anyone here would be able to create a tutorial in the wiki on how to use maven to build a mod. 
Currently maven is only mentioned as a dependency but is not explained. 
Hopefully someone can do this as it would help me and others to make mods.
Cheers

**Comment by alexdriedger** [comment]
I might try to do this

**Comment by alexdriedger** [comment]
Done! The [Getting Started (For Modders)](https://github.com/daviscook477/BaseMod/wiki/Getting-Started-(For-Modders)) wiki page is updated with the Maven tutorial.

@kiooeht This issue can be closed
