### ISSUE TITLE
Too many buttons at resting spots

### ISSUE THREAD

**Issue by Lunaraia** [daviscook477/BaseMod#7]
this might be related to the fact that I am also using the FruityMod - StS to get the The Seeker, but I am getting 2 buttons that both says Forge at resting zones, this is not that bad under normal circumstances, they both function properly, the issue kicks in if you get both Peace Pipe and Girya, with 1 of those that brings the total number of buttons up to 4 and things still work fine, but once you get both Pipe and Girya and enter a resting area you have no buttons at all and get stuck until you abandon the run.

**Comment by daviscook477** [comment]
okay thanks for the heads up.

**Comment by Lunaraia** [comment]
You are welcome, in case it matters I am also using Colored Maps and MoreRelics,

**Comment by daviscook477** [comment]
looks like in the most recent patch they changed up how they add buttons to the campfire UI. It used to be that we had to patch in the smith button for custom characters but now that it's in their by default it looks like that patch should be removed from BaseMod.

**Comment by daviscook477** [comment]
Fixed with https://github.com/daviscook477/BaseMod/releases/tag/v1.9.2
