### ISSUE TITLE
Game crashes when using card with custom buff

### ISSUE THREAD

**Issue by RogerChen98** [daviscook477/BaseMod#82]
I'm making a mod right now and while custom Attack cards work, a custom Skill card that I made keeps crashing the game when it tries to apply a custom debuff. The error log is below, does anyone know what's going on?

![image](https://user-images.githubusercontent.com/23197878/42297542-2e01fbec-7fce-11e8-9244-ff495aa699d4.png)

**Comment by RogerChen98** [comment]
Awesome thanks!

**Comment by kiooeht** [comment]
`loadRegion` shouldn't change anything if you already have `img = ...`
I'm guessing you're having the problem with the Sniper mod on your account. The powers you have uploaded don't have `img` set (though you probably have a more up-to-date version locally that you haven't uploaded).
https://github.com/RogerChen98/STS-SniperMod/blob/master/src/main/java/snipermod/powers/MarkPower.java#L26

**Comment by RogerChen98** [comment]
Yes, that's the one I'm having trouble with.

I'm currently using the `id` of the power and setting the `img` path in the super constructor with the method `loadPowerImg` (it's a static method from the `SniperMod` class). I'll try moving it to the actual `MarkPower` class and see if that changes anything though, maybe I don't know something about the order the constructors do their stuff.

**Comment by kiooeht** [comment]
Ah, I didn't see that. That should work without moving it to `MarkPower`. If it doesn't work after moving, it's possible your images aren't being packaged into your jar. Add a check in the code after you assign `img` to see if it's `null`. You can open your jar in an extraction tool (like 7-Zip) to check if the files were all included properly.

**Comment by RogerChen98** [comment]
Thank you so much, turns out it was just a little problem with my IDE. It changed the .png file's name in all lowercase when it put it into the jar. Nothing else was changed to lowercase before so I never considered it. I probably had it lowercase and renamed it and since it didn't notice any modifications it must've kept it. After deleting my target folder and running `mvn package` again it works perfectly now.
